### ISSUE TITLE
希望能增加一个隐藏式的Menu侧边栏

### ISSUE THREAD

**Issue by rorovic** [ziaochina/mk-app-portal#1]
点击展开或隐藏
样式为
![image](https://user-images.githubusercontent.com/12078430/31336763-f338e4f0-acbd-11e7-8a1e-6334d6b9e7b6.png)

**Comment by ziaochina** [comment]
portal应用已经增加功能，可隐藏菜单

**Comment by rorovic** [comment]
很棒！非常感谢！
